# target: dependencies
# 	action

#Create output file named output
Prog4Main.o: Prog4Main.cpp
	g++ -c Prog4Main.cpp

MicroSecondTimer.o: MicroSecondTimer.cpp MicroSecondTimer.h
	g++ -c MicroSecondTimer.cpp

clean:
	rm *.o
